# fly.toml app configuration file generated for collin-leonard-restore on 2024-04-10T13:05:57-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'collin-leonard-restore'
primary_region = 'iad'

[build]
  image = 'collinleonard/restore:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51P3dbAEQfpqgy10UiYp2d1MV8rJE6MfVZxXjCbujbwVzQux9o8z4HI1SA67HaEAOo9n6L8Jm2CHKvXy3LHAgMlOs00OBdeXKuT"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
